services:
  - type: web
    name: factorium
    env: node
    buildCommand: npm run render-build
    startCommand: node dist/src/start.js
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_VERSION
        value: "22.0.0"
      - key: ALBY_HUB_URL
        value: "https://cincinnati-designers-steps-tips.trycloudflare.com/api"
      - key: ALBY_ACCESS_TOKEN
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtaXNzaW9uIjoiZnVsbCIsImV4cCI6MTgxMDkwOTIxM30.-s8fnI4SsH0wKT6nlCmBljtaFzQVZjrjAosz2g_yWIA"
