services:
  - type: web
    name: factorium
    env: node
    buildCommand: npm run render-build
    startCommand: node dist/src/start.js
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_VERSION
        value: "22.0.0"
      - key: ALBY_HUB_URL
        value: "https://owen-player-project-condo.trycloudflare.com/api"
      - key: ALBY_ACCESS_TOKEN
        sync: false
